version: '3.8'

services:
  skill-sharing-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: skill-sharing-app
    restart: unless-stopped

  # Alternative: Development server
  skill-sharing-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: skill-sharing-dev
    profiles: ["dev"]
